# Generated by Django 5.1.3 on 2024-12-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_principal_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='contact_information',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
