# Generated by Django 5.1.3 on 2024-12-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_teacher_contact_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='not_started', max_length=15),
        ),
    ]
