# Generated by Django 5.1.3 on 2024-12-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
